export const API_REQUEST_SEND = 'API_REQUEST_SEND';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
//auth
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
//users
export const USER_SET_BROWSE = 'USER_SET_BROWSE';
export const USER_SET_SHOW = 'USER_SET_SHOW';
export const USER_DELETE_ITEM = 'USER_DELETE_ITEM';

//orders
export const ORDER_SET_BROWSE = 'ORDER_SET_BROWSE';
export const ORDER_SET_SHOW = 'ORDER_SET_SHOW';
export const ORDER_DELETE_ITEM = 'ORDER_DELETE_ITEM';

export const SALON_SET_BROWSE = 'SALON_SET_BROWSE';
export const SALON_SET_SHOW = 'SALON_SET_SHOW';
export const SALON_DELETE_ITEM = 'SALON_DELETE_ITEM';

export const STATIC_PAGE_SET_BROWSE = 'STATIC_PAGE_SET_BROWSE';
export const STATIC_PAGE_SET_SHOW = 'STATIC_PAGE_SET_SHOW';
export const STATIC_PAGE_DELETE_ITEM = 'STATIC_PAGE_DELETE_ITEM';

export const PROMOTION_SET_BROWSE = 'PROMOTION_SET_BROWSE';
export const PROMOTION_SET_SHOW = 'PROMOTION_SET_SHOW';
export const PROMOTION_DELETE_ITEM = 'PROMOTION_DELETE_ITEM';

export const RATING_SET_BROWSE = 'RATING_SET_BROWSE';
export const RATING_SET_SHOW = 'RATING_SET_SHOW';
export const RATING_DELETE_ITEM = 'RATING_DELETE_ITEM';

//blog
export const BLOG_SET_BROWSE = 'BLOG_SET_BROWSE';
export const BLOG_SET_SHOW = 'BLOG_SET_SHOW';
export const BLOG_DELETE_ITEM = 'BLOG_DELETE_ITEM';

//service
export const SERVICE_SET_BROWSE = 'SERVICE_SET_BROWSE';
export const SERVICE_SET_SHOW = 'SERVICE_SET_SHOW';
export const SERVICE_DELETE_ITEM = 'SERVICE_DELETE_ITEM';

//service items
export const SERVICE_ITEM_SET_BROWSE = 'SERVICE_ITEM_SET_BROWSE';
export const SERVICE_ITEM_SET_SHOW = 'SERVICE_ITEM_SET_SHOW';
export const SERVICE_ITEM_DELETE_ITEM = 'SERVICE_ITEM_DELETE_ITEM';

